[workspace]
resolver = "2"
members = ["agents", "market", "eframe_template", "simulation"]

[workspace.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]